version: "3"

services:
    server:
        build:
            context: ./server
        ports:
            - "34521:34521"

    client:
        build:
            context: ./client
        ports:
            - "3000:3000"